import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

// Initialize the Manrope font from Google Fonts
const manrope = Manrope({
  variable: "--font-manrope", // CSS variable name
  subsets: ["latin"],        // Character subsets to include
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply the Manrope font variable to the body tag.
        This makes it the default font for the entire application.
        The 'antialiased' class smooths out the font.
      */}
      <body className={`${manrope.variable} antialiased`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
